'use strict'

module.exports = {
  CELL_WIDTH: 10,
  EMPTY_CELL: 0,
  RIGHT: 0,
  DOWN: 1,
  LEFT: 2,
  UP: 3,
  STOP: 4,
  DEATH_TIME: 10,
  MAX_PLAYERS: 16,
  TURNS_TO_REFRESH: 50,
  TIME_TO_RESTART: 5,
  GAME_STARTED: 1,
  GAME_NOT_STARTED: 0,
  GAME_WIDTH: 1600,
  GAME_HEIGHT: 1200,
  BOARD_SIZE: 50,
  INTERVAL: 200,
  SCALE: 0.2,
}
